### ISSUE TITLE
Medium severity vulnerability found on brace-expansion@1.1.6

### ISSUE THREAD

**Issue by motss** [isaacs/minimatch#108]
## Description
Vulnerability found on one of the dependencies: `brace-expansion` and the author has released a patch for it. See [brace-expansion fixed ReDoS](https://github.com/juliangruber/brace-expansion/pull/35).

More info: https://snyk.io/vuln/npm:brace-expansion:20170302

## Related issues:

https://github.com/isaacs/minimatch/issues/106

**Comment by plynchnlm** [comment]
Minimatch 3.0.3 already specifies:

"brace-expansion": "^1.0.0"

so it should pick up the new version. Do "npm uninstall brace-expansion" and reinstall.

**Comment by motss** [comment]
Should have fixed
