### ISSUE TITLE
Error when using with Immediately-Invoked Function Expression

### ISSUE THREAD

**Issue by j-medland** [isaacs/minimatch#113]
I appear to be experiencing an unusual error when requiring minimatch in a script with an immediately-invoked-function-expression. For instance the following file

```javascript
const minimatch = require('minimatch')

(function() { /* code */ }())
```
produces the error

```bash
C:\<path>\node_modules\minimatch\minimatch.js:94
    throw new TypeError('glob pattern string required')
    ^

TypeError: glob pattern string required
```

This occurs for `minimatch@3.0.4`
With Node version `v8.7.0`
On Windows 10

On a side note - if I use

```javascript
! function() { /* code */ }()
```
then no error occurs.

**Comment by isaacs** [comment]
The module returns a function.

```js
const minimatch = require('minimatch')

(function() { /* code */ }())
```

is equivalent to:

```js
const minimatch = require('minimatch')(function() { /* code */ }())
```

or:

```js
const m = require('minimatch')
const minimatch = m(function() { /* code */ }())
```

Always prefix your IIFEs with `;` or `!`.
