### ISSUE TITLE
Exclude .test.js files

### ISSUE THREAD

**Issue by gkiely** [isaacs/minimatch#115]
I would like to be able to exclude .test.js files

I've tried the following:
https://stackoverflow.com/questions/26639236/node-glob-pattern-for-every-js-file-except-spec-js

But couldn't get it to work, any ideas?

Here's an example of it:
http://www.globtester.com/#p=eJzT19LSV9TQ0itJLS7RyyrWBAAfCQRI&r=eJyzScksU0jOSSwutlXKTSxJzlCy0w8tTi0q1k%2FJT0%2FVL0stqtRPzE2sStXLKrbRByq2s0HSoYTCg%2BhXKC6pzEm1VUrLzyvRLc6sSrVSMLTUMyqosMZpdElqcQmK%2BXY2SUV2UC6YBAD6Bjlw&

**Comment by isaacs** [comment]
Minimatch support for globstar is limited.  For proper globstar behavior, you must use glob itself.

Without the globstar it works, though.

```
$ tree
.
├── amaze.js
└── amaze.test.js

0 directories, 2 files

$ for i in ./!(*.test).js; do echo $i; done
./amaze.js

$ node -p 'require("glob").sync("./!(*.test).js")'
[ './amaze.js' ]

$ node -p '["./amaze.test.js","./amaze.js"].filter(require("minimatch").filter("./!(*.test).js"))'
[ './amaze.js' ]
```

**Comment by gkiely** [comment]
Ok thanks for clarifying that.
