### ISSUE TITLE
Identical strings don't match if they end on a space

### ISSUE THREAD

**Issue by TanninOne** [isaacs/minimatch#117]
As the title says, this returns false:
```
const minimatch = require('minimatch');
minimatch("test ", "test ");
```

**Comment by isaacs** [comment]
Oh, actually, no, they don't get trimmed in v4 and higher.  For a second this was a bug in 3.0, but that's fixed now (so this again doesn't work in v3, as it should).  In v4 and v5, this issue is corrected.
