### ISSUE TITLE
Minimatch treats timezone's slash as new route separator in endpoint route's definition

### ISSUE THREAD

**Issue by asadaj** [isaacs/minimatch#120]
I am using Cypress.io to test my application and have stumbled upon this issue while stubbing an endpoint for my application. 

Here are the results of the matching: 

Cypress.minimatch('/api/export?timezone=Europe/Warsaw', '**/export*/**', {
  matchBase: true
}) // true

Cypress.minimatch('/api/export?timezone=Europe/Warsaw', '**/export**', {
  matchBase: true
}) // false

The second example shows that you have to use the stars twice if you don't care about the timezone's actual value (which is containing two parts, separated by a slash). It is non intuitive, as user has to use two sets of stars to stub the response for the parameters like timezone, when in reality it is only one parameter, so one would anticipate that only one star would be enough.

**Comment by isaacs** [comment]
Yeah, you shouldn't parse URLs with globs.  Use a URL parser.

Maybe `Cypress.minimatch` should be just applying minimatch against `new URL(path).pathname` or something?

Either way, minimatch is doing the right thing here.
