### ISSUE TITLE
Regex and non-Regex results differ

### ISSUE THREAD

**Issue by kingces95** [isaacs/minimatch#124]
I expected the following to print `true` in both cases. It actually prints `false` and `true`. The regex version fails to match `bar.js` when given pattern `**/*.js`. I'm using the latest version as of this post. 

```js
var minimatch = require('minimatch')

var string = 'bar.js'
var pattern = '**/*.js'

console.log(minimatch.makeRe(pattern).test(string))
console.log(minimatch(string, pattern))
```

**Comment by kingces95** [comment]
Similar to https://github.com/isaacs/minimatch/issues/62. Seems the regex version doesn't match the latebound version. :(

**Comment by Vigilans** [comment]
Reproduced the same result:
```javascript
> minimatch(".DS_Store", "**/.DS_Store")
true
> minimatch.makeRe("**/.DS_Store").test(".DS_Store")
false
```

But micromatch will return correctly:
```javascript
> micromatch.makeRe("**/.DS_Store").test(".DS_Store");
true
```
