### ISSUE TITLE
*.{json} pattern works incorrect

### ISSUE THREAD

**Issue by lamartire** [isaacs/minimatch#126]
Guess this behaviour is incorrect

```js
minimatch('foo.json', '*.{json,yaml}') // true
minimatch('foo.json', '*.{json}') // false
```

**Comment by roggervalf** [comment]
hi @lamartire, this is related to brace-expansion behavior, as this package only accepts sh/bash format, the expansion of 1 value is not allowed, so it does not delete {}.

**Comment by isaacs** [comment]
Yeah, this is working as designed, matching bash v4+ behavior.
