### ISSUE TITLE
Incorrect matching with slash prefix

### ISSUE THREAD

**Issue by lamartire** [isaacs/minimatch#127]
Guess it should also match with this pattern

```
minimatch('foo.json', '*.json') // true
minimatch('/foo.json', '*.json') // false
```

**Comment by mogafk** [comment]
start with **./** same problem

**Comment by kristinochka** [comment]
Having a slash anywhere in the path breaks the match:
minimatch('Hello/hello.txt', '*.txt') --> false

**Comment by isaacs** [comment]
Working as intended.  `*` doesn't match `/`.  Set `{matchBase:true}` in the options arg if you want to mach against just the basename portion of a path containing slashes.

```
> minimatch('Hello/hello.txt', '*.txt')
false
> minimatch('Hello/hello.txt', '*.txt', {matchBase: true})
true
```
