### ISSUE TITLE
Problem with makeRe

### ISSUE THREAD

**Issue by Domajno** [isaacs/minimatch#132]
I was under the impression that `pattern.test("tests/unit/before.spec.ts")` should evaluate to `true`. Is this a bug or I am doing something wrong?

```
> var minimatch = require("minimatch")
undefined
> minimatch("tests/unit/before.spec.ts", "tests/unit/**/*.ts")
true
> var pattern = minimatch.makeRe("tests/unit/**/*.ts");
undefined
> pattern.test("tests/unit/before.spec.ts")
false
```

**Comment by Nokel81** [comment]
I too have run into this, it seems like `makeRe` doesn't produce a regexp that matches the same as `minimatch` (the function) does...

**Comment by isaacs** [comment]
This has long been a shortcoming of makeRe, but the latest version does support this now.
