### ISSUE TITLE
The documentation doesn't contain adequate reference

### ISSUE THREAD

**Issue by emahuni** [isaacs/minimatch#147]
I have been trying to figure out the actual matching patterns used. I know the normal glob patterns, but was thinking it's different. Your documentation points to man pages that don't really do justice for this small piece of info.

I googled and came across this, maybe link that in the readme instead:

https://github.com/motemen/minimatch-cheat-sheet

It's much more helpful.

**Comment by isaacs** [comment]
Doc patches always welcome.
