### ISSUE TITLE
Match fails if tested string contains slash

### ISSUE THREAD

**Issue by thybzi** [isaacs/minimatch#151]
Minimatch 3.0.4 doesn't match if tested string contains slash.

The most simple example is:
```javascript
minimatch('foo bar', 'foo*'); // => true
minimatch('foo/bar', 'foo*'); // => false
```

Is it an expected behavior? How can I override it?

P.S. I've looked through all issues mentioning slashes, but most of them are about the dot, and then one of timezones (#120) seemed to be about pattern, not tested string

**Comment by isaacs** [comment]
Yeah, this is how glob works.  `*` doesn't match `/`.

Maybe you could use `/**` to mean "zero or more path portions"?

```
> minimatch('foo/bar', 'foo*/**')
true
```
