### ISSUE TITLE
3.0.7 breaks cucumberJS step definitions

### ISSUE THREAD

**Issue by ealmiladi** [isaacs/minimatch#156]
`3.0.7` that was released two days ago broke our CucumberJS integration at our company. While we're not exactly sure what might be broken, all of our cucumber step definitions are resolving as undefined. 

E.g.

```
import { Given } from '@cucumber/cucumber';

Given('I have {int} cucumbers in my belly', function (cucumberCount) {
  assert.equal(this.responseStatus, cucumberCount)
});
```

When attaching the step definitions to the cucumber CLI runner and executing a test, the test runner is no longer recognizing these step definitions on v `3.0.7`.

We had to pin `3.0.4` under the `resolutions` block of `package.json` in order to circumvent `>3.0.7` and resolve the issue. Many of our dependencies rely on subdependencies that include this project and are now resolving to the `3.0.7` release which includes either a bug or breaking changes.

**Comment by isaacs** [comment]
As you have a workaround, and the only solution is to roll back a security fix (since pinning won't pin your deps anyway) I'd like to investigate what's happening here. 

Do you have a repro you can share?

**Comment by isaacs** [comment]
Oh, no such luck.

Ok, I need a reproduction case.  Nothing changed that should've caused this, so I'm stumped.

**Comment by isaacs** [comment]
This is the entirety of the changes from 3.0.4 to 3.0.7 https://gist.github.com/isaacs/ea62d80f51eed1b6eeae37baeef2ff38

**Comment by ealmiladi** [comment]
Thanks for looking. We've created a repro and left instructions to reproduce on the `README`: https://github.com/ealmiladi/cucumber-js-minimatch

**Comment by ealmiladi** [comment]
I've isolated the change that is causing our issues:

<img width="1531" alt="image" src="https://user-images.githubusercontent.com/27777704/154134813-f5b9eb67-7343-403a-9d7a-6053258a359d.png">

**Comment by isaacs** [comment]
Aha, I see, so it looks like the pattern.trim() went missing, and that's what broke it.  Easy enough to fix.  Stand by.

**Comment by isaacs** [comment]
Should be fixed on 3.0 and 3.1 now.  Care to test?

**Comment by ealmiladi** [comment]
Awesome, thank you! I'm waiting for these versions to hit NPM to test.

**Comment by ealmiladi** [comment]
Worked perfectly, thank you.
