### ISSUE TITLE
Match folder with optional leading and trailing folders

### ISSUE THREAD

**Issue by ade-verd** [isaacs/minimatch#168]
Hi, 

I would like to match every paths that contains `foo` in the following paths:
```
../../foo/bar/abc
../../foo/bar
../../foo
../foo
./foo
foo
```

I tried to use the pattern `**foo**` but it didn't work.

While using the `debug` option, I can see the regex: `'(?!\\.)(?=.)[^/]*?[^/]*?foo[^/]*?[^/]*?'`
This regex seems matching all my paths. So I'm not sure to understand.

My closest solution was to use the pattern `foo` associated with `{ matchBase: true }`.
But it doesn't work when `foo` has trailing path.

Do you have any idea ?

___

Note: I am not able to use regex, because I am indirectly using `minimatch` with [eslint-plugin-import](https://github.com/import-js/eslint-plugin-import/blob/main/src/rules/order.js#L326)

**Comment by isaacs** [comment]
`**` is only relevant when it's the only contents of a path portion. Try `./**/foo/**`

**Comment by ade-verd** [comment]
Thanks for your answer @isaacs 
But it doesn't work either

You can find here some simple tests: https://onecompiler.com/nodejs/3y2p59aqp

**Comment by derek-h-kim** [comment]
any update on this? I also have a very similar use case to OP

**Comment by kimurakenshi** [comment]
I'm also trying to achieve this. Does anyone know if it is possible? I believe the above answer doesn't cover scenarios like '../../foo' for example.

**Comment by isaacs** [comment]
Oh, you want to go _up_ the folder tree?  In that case, you have to provide the `..` portions explicitly.  `**` will not match the `.` or `../` directory entries, by design, because otherwise `$ echo **/foo` on your shell would have to search _your entire computer_.

For the case described, the pattern `'{,./,../,../../}**/foo{,/**}'` will do what you're describing.  But if you want to match any arbitrary number of `../` portions, sorry, this isn't going to be able to do that.

**Comment by Mex505** [comment]
Could you help me get my tokens back and ill pay you but i also need help despositing my crypto to my bank thats where i messed up in the first place. Thank you

**Comment by isaacs** [comment]
You could also just remove the `../` portions prior to testing, or use `path.join()` to remove them from everywhere.

But really, this should be a big red flag. If you're hoping to match .. path portions with a glob, you're probably opening yourself up to some security issues, or at least, very weird behavior. What if the path is `./foo/../bar`? If `**/foo/**` matched that, then you'd be matching the effective path of `./bar`, which doesn't have `foo` in it. 

Back up a step, and see if there's another way around. How did you end up having this use case? Something is probably weird there, or could be addressed in a more elegant way. If you share the situation, I'd be happy to help think it through if I can.
