### ISSUE TITLE
Reason behind short max pattern length

### ISSUE THREAD

**Issue by lukehaas** [isaacs/minimatch#173]
I'm receiving the error `pattern is too long`. This is due to my pattern exceeding the `MAX_PATTERN_LENGTH ` which is set to `1024 * 64`.
I wondered what is the reason behind this limit?

I'd be happy to raise a PR to increase it if that's ok.

**Comment by isaacs** [comment]
This is a regular expression denial of service protection.  I'd be open to a PR to make it configurable, with 64*1024 as the default, but I'd also encourage you to think carefully about what you're doing and see if there's a way to _not_ have a glob pattern that is more than 64kb in size.

**Comment by lukehaas** [comment]
@isaacs thanks for the quick response. Good to know this limit is for denial of service protection.
A solution was found for reducing the size of the glob pattern.
