### ISSUE TITLE
Cannot find name 'readonly'

### ISSUE THREAD

**Issue by Dhaval8087** [isaacs/minimatch#176]
My react app not working anymore after the update from **Wed, 24 Aug 2022 08:32:18 GMT**

typescript complain about the below-mentioned error 

path : node_modules/@types/minimatch/index.d.ts

error : (29,26): Cannot find name 'readonly'.

**Comment by fdenou** [comment]
I have the same problem. The fix seems to be done on https://github.com/DefinitelyTyped/DefinitelyTyped/commit/46a35771cb8033099e820124350415e2ffcf6f4b but not taken into account here

**Comment by Mex505** [comment]
What is it that you want from me what information are you looking for. Just wondering why you want to get in contact  with me.

**Comment by isaacs** [comment]
Types for this library are only handled by DT, not here.

**Comment by Mex505** [comment]
Hello i have a question how much crypto did i accidently send out to people. Can i get it back. It was a stupid mistake. Thank you for your help.
