### ISSUE TITLE
error TS1005: ',' expected.

### ISSUE THREAD

**Issue by nitin1104** [isaacs/minimatch#177]
Getting this error on building the application with prod params

ERROR in node_modules/@types/glob/node_modules/@types/minimatch/index.d.ts(29,35): error TS1005: ',' expected.
node_modules/@types/glob/node_modules/@types/minimatch/index.d.ts(29,41): error TS1005: ',' expected.
node_modules/@types/glob/node_modules/@types/minimatch/index.d.ts(42,59): error TS1005: ',' expected.
node_modules/@types/glob/node_modules/@types/minimatch/index.d.ts(42,65): error TS1005: ',' expected.
node_modules/@types/glob/node_modules/@types/minimatch/index.d.ts(271,33): error TS1005: ',' expected.
node_modules/@types/glob/node_modules/@types/minimatch/index.d.ts(271,39): error TS1005: ',' expected.

Angular version: 5
TS version: 2.7.2

**Comment by isaacs** [comment]
These are errors coming from the DefinitelyTyped definitions.  I don't maintain those, sorry.

**Comment by nitin1104** [comment]
Appreciated your quick response Thanks
