### ISSUE TITLE
Problem with nocase and relative pathes

### ISSUE THREAD

**Issue by DavidMansolino** [isaacs/minimatch#178]
We have a problem when using the nocase option together with relative pathes.
The ``..`` is transformed in a regex (whereas it is not if nocase is false) and there is no match with it.

Here is an example:
```js
var files = glob.sync('../../../tools/pipelines/run*.bat', {debug : true, nocase : true, dot: true });
```

The result of the decomposition of the path (with and without nocase):

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/2461619/193213373-4879a56b-cf5b-48ca-a694-f454adca18ab.png)

This seems related to:
https://github.com/isaacs/minimatch/blob/main/minimatch.js#L428

P.S.: we are on Windows.

**Comment by isaacs** [comment]
Can you try with minimatch 5.1.4?  I think this might be a glob bug rather than a minimatch bug, but it seems like turning `..` into a regexp unnecessarily _may_ be part of the problem.

**Comment by Shaun0703** [comment]
Hi all is there anything i can do to help?

**Comment by isaacs** [comment]
This issue was fixed already, but thanks for the offer :) 

https://github.com/isaacs/minimatch/commit/d2c654d020f03745c02e96b506a2178d024c9c40
