### ISSUE TITLE
`foo/**` should not match `foo/`

### ISSUE THREAD

**Issue by mdjermanovic** [isaacs/minimatch#179]
I would expect that `foo/**` matches everything inside the directory `foo`, but not the directory itself.

```js
const minimatch = require("minimatch");

minimatch("foo/", "foo/**"); // true, but it should be false.
```

**Comment by isaacs** [comment]
> I would expect that foo/** matches everything inside the directory foo, but not the directory itself.

That expectation is incorrect.

```bash
$ mkdir -p foo/bar/baz

$ echo foo/**
foo/ foo/bar foo/bar/baz
```

Working as intended :)

**Comment by isaacs** [comment]
You can use `foo/*/**` to match "everything 1 or more directory levels under `foo/`" though.
