### ISSUE TITLE
Upgrade from 3.0.4 -> 5.1.0. Any breaking changes?

### ISSUE THREAD

**Issue by mtdvlpr** [isaacs/minimatch#182]
Hi, I want to forcefully update my dependencies to use minimatch@5.1.0. Some are currently using 3.0.4. Are there any breaking changed in between those versions or can I safely update?

**Comment by 1990eam** [comment]
I second this. Is there a changelog available?

**Comment by isaacs** [comment]
Good nag, thanks.
