### ISSUE TITLE
v6.1.4 is missing in the npm registry

### ISSUE THREAD

**Issue by lisadean** [isaacs/minimatch#191]
```
$ npm i minimatch
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/minimatch/-/minimatch-6.1.4.tgz
npm ERR! 404 
npm ERR! 404  'minimatch@^6.1.3' is not in the npm registry.
```

**Comment by damnhandy** [comment]
Seeing the same thing

**Comment by sentient-momeni** [comment]
Same. Is there any updates on when this would be available?

**Comment by damnhandy** [comment]
@sentient-momeni seems like all versions are gone?

**Comment by Sdocquir** [comment]
Same here. Currently blocking CI/CD for our project.

**Comment by broffis** [comment]
We're able to get our CI/CD to run by pinning to `6.0.4`. Seems like `@latest` is missing from npm registry

**Comment by Sarah-clariondoor** [comment]
<img width="1387" alt="Screen Shot 2023-01-17 at 1 04 08 PM" src="https://user-images.githubusercontent.com/42549181/213011951-9d7043a2-f47f-4626-a7b7-11d4f25f149b.png">
Seeing the same thing for the yarn registry.

**Comment by damnhandy** [comment]
For our needs, we traced the dependency back to Jest. We updated to jest version 29.x, which curiously uses `minimatch 3.1.4` instead. Now we are unblocked. `npm ls minimatch` is your friend.

**Comment by sentient-momeni** [comment]
It's fixed 🎉 @damnhandy and everyone else

**Comment by damnhandy** [comment]
Yeah, that is weird. Would be nice to know why `v6` disappeared for a while and suddenly reappeared?

**Comment by isaacs** [comment]
Seems like this was just an npm registry issue.  I did nothing to fix it.
