### ISSUE TITLE
Provide more examples of expected matches for globstar

### ISSUE THREAD

**Issue by gajus** [isaacs/minimatch#196]
```ts
minimatch('/contra/gaia-og/node_modules/.pnpm/react-style-singleton@2.2.1_3stiutgnnbnfnf3uowm5cip22i/node_modules/react-style-singleton/dist/es2015/index.js', '**/es2015/**')
```

I am confused why this does not match.

Based on my understanding of globstar and the examples provided, I would expect this to match.

I also tried `partial` flag, but it does not match either:

```ts
minimatch('/contra/gaia-og/node_modules/.pnpm/react-style-singleton@2.2.1_3stiutgnnbnfnf3uowm5cip22i/node_modules/react-style-singleton/dist/es2015/index.js', '**/es2015/**', {partial: true})
```

I am not clear how is this supposed to be used.

For clarity, I want to check if an arbitrary path contains `es2015` directory.

**Comment by gajus** [comment]
It seems like if I add `{ dot: true }` option, it works, but I don't understand why it is needed – my file does not start with a dot.

>  Allow patterns to match filenames starting with a period, even if the pattern does not explicitly have a period in that spot.

Perhaps the documentation is inaccurate in that it states that it will match files beginning with a dot, but really seem to mean that it will break if dot exists at the beginning of any segment of the path.

**Comment by isaacs** [comment]
The `**` will not match against `.pnpm`, because it starts with a dot.

This is by design, matching Bash 5 behavior.  Happy to take a docs patch if you'd like to help clarify the wording there, I can see how it could be interpreted how you read it.
