### ISSUE TITLE
Error: Cannot find module 'brace-expansion'

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [isaacs/minimatch#204]
It seems there is a problem with module resolution in some way.
![image](https://user-images.githubusercontent.com/86342787/227899881-9eda6e0e-e04f-49bb-b76e-798ddb0fd02e.png)

**Comment by isaacs** [comment]
`brace-expansion` is pretty clearly listed as a dep in package.json.  What does `npm ls brace-expansion` show?

**Comment by isaacs** [comment]
(closing but happy to reopen if something is indeed broken)

**Comment by sschneider-ihre-pvs** [comment]
There are a lot of packages with a dependency to brace-expansion, but indeed, it seems to be some kind of system hickup, no idea why it could not be found.

**Comment by OkponkoXchange** [comment]
The most important aspect is to make a plan and make sure you have time and space in mind when planning
