### ISSUE TITLE
Webpack build is failing since 7.1.1

### ISSUE THREAD

**Issue by UnchartedBull** [isaacs/minimatch#205]
Hi,

I'm having some problems with using minimatch within an Angular app (thus I do not have access to the node variables and such). This was not a problem for minimatch before probably this commit https://github.com/isaacs/minimatch/commit/58917fece99321883b6fccdac9520d867a95e617. 

With the line change here: https://github.com/isaacs/minimatch/blob/5139e19188b9fea0cbd9064a17b40551d6ddc23d/src/index.ts#L25 this now results in an error when building:

```
Error: node_modules/minimatch/dist/cjs/index.d.ts:63:22 - error TS2591: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node` and then add 'node' to the types field in your tsconfig.

63     platform: typeof process.platform;
                        ~~~~~~~

```

Would be great if this could be optional similar to how the other node dependent code is handled.

**Comment by UnchartedBull** [comment]
Thanks for fixing this so quickly. It seems like this was the only occurrence of `process.platform`:

https://github.com/isaacs/minimatch/blob/cb1b69080ca4f972ce913e2a7ea6720a14b96e39/src/index.ts#L110
https://github.com/isaacs/minimatch/blob/cb1b69080ca4f972ce913e2a7ea6720a14b96e39/src/index.ts#L311

The build is still failing with the same error:

```
Error: node_modules/minimatch/dist/cjs/index.d.ts:20:23 - error TS2591: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node` and then add 'node' to the types field in your tsconfig.

20     platform?: typeof process.platform;
                         ~~~~~~~


Error: node_modules/minimatch/dist/cjs/index.d.ts:67:22 - error TS2591: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node` and then add 'node' to the types field in your tsconfig.

67     platform: typeof process.platform;
                        ~~~~~~~
```

Sorry for bugging you again.

**Comment by isaacs** [comment]
Ok, should work now.  Got rid of all references to NodeJS.Platform type on v7 and v8 latest publishes.
