### ISSUE TITLE
Debug info does not seem to match end result of minimatch

### ISSUE THREAD

**Issue by awayken** [isaacs/minimatch#218]
I'm using minimatch to verify if a given URL matches a specific URL pattern to determine if I should add a special header to the network request my application is making. It doesn't seem to be correctly reporting the match.

I've turned on debug mode to see where things are going wrong. The messages show `true` for every segment of the URL, yet the end result is still `false`. I don't know what I'm doing wrong. I've included a (slightly modified) version of my code and a screenshot of the debug output.

Code sample:
```ts
  const optionalResources = new Map<string, (string | ProtectedResourceScopes)[] | null>([
    [`https://dev-api.website.com/audit-api/*`, null],
  ]);

  hasScopesForEndpoint('https://dev-api.resolve.com/audit-api/action/page');

  function hasScopesForEndpoint(url: string): boolean {
    let hasMatchedForNull = false;

    optionalResources.forEach((value: (string | ProtectedResourceScopes)[] | null, key: string) => {
      const hasMatched = minimatch(url, key, {
        debug: true,
        nocase: true,
      });
      console.log('hasMatched', hasMatched);

      if (hasMatched) {
        hasMatchedForNull = hasMatched;
      }
    });

    return hasMatchedForNull;
  }
```

Results of the debug logs:
![image](https://github.com/isaacs/minimatch/assets/156215/6e7fe060-00e1-421b-b677-1223751434f9)

It looks to me like it clearly matches at every segment of the URL I'm testing, yet then the end result of "hasMatched" is false. Am I missing something?

Any direction would be very helpful. Thank you!

**Comment by isaacs** [comment]
The issue is that `*` only matches a single path portion. Try `https://dev-api.website.com/audit-api/**`

**Comment by isaacs** [comment]
To answer the question about the confusing debug output, every pattern portion matches a path section, but then there are more path sections left over and no remaining pattern portions to match them, so it's not a match.

**Comment by awayken** [comment]
That makes sense. I made the update, and it's matching now. This explains the debug info more, too. I figured it was a "me" problem. Thanks!
