### ISSUE TITLE
Paths starting with ../ are not matched against **/, e.g: minimatch('../file.json', '**/file.json')

### ISSUE THREAD

**Issue by greenpixels** [isaacs/minimatch#230]
Hey there,
I wanted to use minimatch to traverse files in a parent directory, but also wanted to exclude node_module-paths.

Took me a while to figure out that this does not seem to be possible with minimatch, as
`minimatch('../node_modules/path/to/any/file.ts', '**/node_modules/**')` returns `false`

Maybe this is expected behaviour, but I couldn't find anything specifically describing this in the ReadMe.md

**Comment by isaacs** [comment]
Well, yeah, if you do `echo **/node_modules/**` then it's only going to find files and folders in the current directory, not the parent. `**` doesn't ever match `../`. Maybe what you want is `../**/node_modules/**`?
