### ISSUE TITLE
[bug]: `**/*.env` or `*.env` doesn't match `.env`

### ISSUE THREAD

**Issue by shulaoda** [isaacs/minimatch#233]
```js
> console.log(require('minimatch').minimatch('.env', '*.env'))
false
```
or
```js
> console.log(require('minimatch').minimatch('.env', '**/*.env'))
false
```

**Comment by isaacs** [comment]
Path portions that start with a `.` are not matched unless the pattern path portion starts with a `.` or `dot: true` is set in the options, just like command line argument globs. 

Eg, `$ echo *.env` won't find the file either. 

Working as intended.
