### ISSUE TITLE
Where is the pattern grammar docs?

### ISSUE THREAD

**Issue by TWiStErRob** [isaacs/minimatch#237]
I'm using Renovate which [only documents that it's using this library](https://docs.renovatebot.com/string-pattern-matching/), but after reading this repo's readme, I'm still not sure what the actual syntax is.

I'm looking for reference docs like this: https://docs.python.org/3/library/re.html#regular-expression-syntax

**Comment by isaacs** [comment]
I'm not sure that there is a defined pattern grammar for glob expressions. The reference implementation that this library targets is Bash v5. Run `man bash` and search for `Pattern Expansion` to see a pretty comprehensive explanation. The [glob readme](/isaacs/node-glob) also has some information about it.

Patch welcome if anyone would like to create such a document. I've never found that it to be necessary, myself.
