### ISSUE TITLE
Please support Node 18

### ISSUE THREAD

**Issue by simatec** [isaacs/minimatch#238]
Please support Node 18 for the current version of minimatch.
Node 18 is current and not end of life.
Many users use Node 18 and with an upgrade to minimatch 10.0.1 there was a crash

**Comment by daigang1228** [comment]
+1

**Comment by daigang1228** [comment]
help!!!!!!!

**Comment by daigang1228** [comment]
@isaacs please check thanks

**Comment by isaacs** [comment]
So don't use the latest version. Use minimatch 9 if you're using node 18.

I am saying this as a courtesy in the hopes that it's new information which you will use to adjust your behavior accordingly: Spamming issues with entitled demands like this is extremely rude. This is why maintainers flip the table and walk away from OSS forever. I will block you from interacting with my repositories if it continues.
