### ISSUE TITLE
Simpler exclusion pattern when globbing

### ISSUE THREAD

**Issue by aaronbushnell** [isaacs/minimatch#25]
When I try to exclude a directory (and its files) from a glob, I need to write out the pattern like this:

```js
[
  'app/**',
  '!app/{_tmp,_tmp/**}'
]
```

Just using this:
```js
[
  'app/**',
  '!app/_tmp/**'
]
```

would copy over the directory, but will not contain any files. While using this:
```js
[
  'app/**',
  '!app/_tmp/'
]
```

would copy over `_tmp` and its files.

Is there any way to simplify this pattern? It seems like just using `'!app/_tmp/**'` should be sufficient to exclude the directory entirely.

(Referencing gulpjs/gulp#165)

**Comment by vossad01** [comment]
+1

**Comment by mark-zacharias** [comment]
+1

**Comment by isaacs** [comment]
You can do explicit ignores with glob now, but this is not (and likely won't ever be) supported in minimatch.

```
glob('**', { ignore: 'app/{_tmp,_tmp/**}' }, cb)
```
