### ISSUE TITLE
minimatch.makeRe ignores flipNegate

### ISSUE THREAD

**Issue by Qix-** [isaacs/minimatch#28]
It appears `minimatch.makeRe("*1.js", {"flipNegate":true, "matchBase":true})` for `{a.js, a1.js}` still returns `a1.js` instead of `a.js` when using it with `filename.match(miniRegexp)`.

Is it ignoring it, or am I missing something?

**Comment by isaacs** [comment]
`flipNegate` doesn't turn negation on and off.  It makes the Minimatch object walker match the path against the base pattern whether negated or not.  It's intended for cases (like parsing ignore files) where you need to know whether something was actually found and negated, or just not found in the path entry set.

Not the best name for it.  But yeah, if you aren't negating the pattern like `'!*1.js'`, then flipNegate will do exactly nothing.
