### ISSUE TITLE
Negating patterns not working

### ISSUE THREAD

**Issue by jnordberg** [isaacs/minimatch#4]
Patterns using extglob negating groups never matches. e.g. `*.!(js)`

**Comment by chinchang** [comment]
@jnordberg were you able to run the mentioned pattern. I am not able to run negating group.

**Comment by jnordberg** [comment]
Yeah it works

**Comment by chinchang** [comment]
Did you use any other option apart from setting `nonegate` as `true`?

**Comment by jnordberg** [comment]
Maybe you want **no**negate set to false? 😆

**Comment by chinchang** [comment]
By default, expressions starting with ! are negated. By in my case I don't want to the complete expression, but instead just the group following `!`. Isn't this the use case of setting `nonegate` to true?
BTW, my expression is `!(abc)**package.json`. I don't want to match `package.json` that is inside `abc` folder.

**Comment by jnordberg** [comment]
🤷‍♂️ works for me
