### ISSUE TITLE
Problem with exclusion syntax

### ISSUE THREAD

**Issue by arthurmchr** [isaacs/minimatch#43]
I am currently facing a problem using minimatch syntax through gulp for a simple task.

Here is how my files are organized :

```
public/
____app/
________file4.txt
________js/
____________admin/
________________files1.txt
________________files2.txt
____________otherfolder/
________________files3.txt
____________file4.txt
```

I am trying to get all files included in app (only file4.txt in my example) and in the app/js/admin folder (files1.txt & files2.txt).

Here is my glob syntax :

```
['public/app/js/admin/**/*.txt', '!public/app/js/**', 'public/app/**']
```

With this command, it only return file4.txt and an empty js folder.

Thanks for your help !

**Comment by AndrewEastwood** [comment]
can somebody assit me with the follwing: need to exclude subfolder "var" out from the tree:

test/doge/very/amaze.js
test/local/bin/wow.js
test/local/bin/zz/g.js
test/var/com/f.js
test/var/com/ss/t.js
test/var/com/hh/ff/t.js
test/var/com/xx/gg/hh.js

**Comment by isaacs** [comment]
This really seems like a gulp issue, not a minimatch issue.  It might be worth looking at how ignore-walk and npm-packlist do this, perhaps gulp could use a similar approach.
