### ISSUE TITLE
Add "files" entry in package.json to ignore everything but listed there

### ISSUE THREAD

**Issue by rubennorte** [isaacs/minimatch#60]
In this package I suppose only minimatch.js is required when installed in production mode, so you just need to add this in the package.json:

``` json
{
  "files": [
    "minimatch.js"
  ]
}
```

See https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package for more info.

Thanks.

**Comment by slang800** [comment]
See https://github.com/isaacs/minimatch/pull/37#issuecomment-43945466, which was in response to a PR that did the same thing, but using `.npmignore`:

> Thanks, but the tests are included for a reason.

I'm not totally sure what the reason is that @isaacs has in mind, but I'd love to hear it since I'm excluding tests from all my packages atm.
