### ISSUE TITLE
Incorrect slash substitution on Windows platform

### ISSUE THREAD

**Issue by thbecker** [isaacs/minimatch#64]
In minimatch.js, function [Minimatch](https://github.com/isaacs/minimatch/blob/master/minimatch.js#L114) back-slash characters in the pattern get replaced by forward-slashes when running on Windows platform. This isn't necessary since glob [requires](https://www.npmjs.com/package/glob#windows) that only forward-slashes are used in paths. It is also wrong because patterns can contain back-slashes. For example it breaks 'npm help npm' on Windows (no man pages are found) because [help.js, line 66](https://github.com/npm/npm/blob/master/lib/help.js#L66) uses a pattern with a back-slash that mustn't be converted to a forward-slash (which is then interpreted as a path separator and breaks the pattern).

I suggest not to convert slashes in minimatch because it would be hard to distinguish slashes in paths from slashes in patterns but to leave path conversion to the caller, e.g.
`var manroot = path.resolve(__dirname, "..", "man").split("\\").join("/")`
in [help.js, line 59](https://github.com/npm/npm/blob/master/lib/help.js#L59).

**Comment by yortus** [comment]
Related: https://github.com/isaacs/node-glob/issues/212

**Comment by ericsciple** [comment]
fyi - i've found some workarounds for escaping on Windows:
`@(hello)` => `@(@)(hello)`
`+(hello)` => `@(+)(hello)`
`!(hello)` => `@(!)(hello)`

and `[ab]` => `[[]ab]`

**Comment by ericsciple** [comment]
or a little bit simpler syntax would be `[@](hello)`, etc

**Comment by litmit** [comment]
Forward slash in glob pattern should match both forward and back slashes in filepath on Windows!
Converting slashes in glob pattern as it does minimatch is completely erroneous way.

**Comment by isaacs** [comment]
v3 0b5dea1
v5 9104d8d
