### ISSUE TITLE
negative matches unclear

### ISSUE THREAD

**Issue by tcurdt** [isaacs/minimatch#70]
I want to

```
match "design/**/*"
except "design/templates/*"
```

maybe something like this could work

```
"design/!(templates)**/*"
```

but that's really not clear from the docs.

**Comment by zwhitchcox** [comment]
Yes, this is possible! The two stars don't really make sense though. that only works if the two stars are the only thing in the directory name, for example '/**/'. Otherwise, they're just treated like a single star. Also, a '!' at the beginning will negate the entire pattern.

**Comment by tcurdt** [comment]
What does the `{,/**}` mean? Optional? Why the `,`?

**Comment by zwhitchcox** [comment]
The curly braces and comma add another pattern. It's basically like writing

```design/!(templates) or design/**```
