### ISSUE TITLE
Match specific files in directory

### ISSUE THREAD

**Issue by karneaud** [isaacs/minimatch#74]
I'm tying to match particular files in directory

I'm trying to use `path/to/directory/{ajax.js,data.js}` pattern but doesn't work. Would it be able to use such a patter?

**Comment by isaacs** [comment]
Works for me.

```
> minimatch('path/to/directory/data.js', 'path/to/directory/{ajax.js,data.js}')
true
> minimatch('path/to/directory/ajax.js', 'path/to/directory/{ajax.js,data.js}')
true
> minimatch('path/to/directory/some other thing', 'path/to/directory/{ajax.js,data.js}')
false
```

If you want to find files on the filesystem using a pattern, probably what you want is [glob](http://npm.im/glob)
