### ISSUE TITLE
Using minimatch on Windows?

### ISSUE THREAD

**Issue by rauschma** [isaacs/minimatch#78]
If I traverse a directory on Windows via `fs.readdir()` and `path.resolve()`, will minimatch work? Could you include the answer in the readme file? I don’t have a Windows machine, but am curious if my command line tool would work on one.

From the following interaction, I’d guess that the answer is “no”:

```
> mm('a\\b\\c.txt', 'a/**/*.txt')
false
```

**Comment by rauschma** [comment]
This sounds like a good solution for Windows: https://github.com/isaacs/minimatch/issues/64

Suggestion: add a section on Windows paths to the readme.

**Comment by szarouski** [comment]
@isaacs will it help if I add a note about windows backslashes to readme? Thanks.

**Comment by isaacs** [comment]
Doc patches always welcome.

**Comment by isaacs** [comment]
v3 https://github.com/isaacs/minimatch/commit/0b5dea151f7ce9605f24db19715a6a4a08da7594
v5 https://github.com/isaacs/minimatch/commit/9104d8d175bdd8843338103be1401f80774d2a10
