### ISSUE TITLE
matching files that start with a . (dot)

### ISSUE THREAD

**Issue by lleo** [isaacs/minimatch#79]
first as an example:

```
bash-3.2$ echo .*.sh
.clojure.sh .pathfunctions.sh
```

in the REPL of Node v5.0.0

```
> minimatch = require('minimatch')
...stuff...
> minimatch('.*.sh', '.clojure.sh')
false
 ... ok well read the docs better
> minimatch('.*.sh', '.clojure.sh', {dot: true})
false
  ... not good
> mm = new minimatch.Minimatch('.*.sh', {dot: true})
...stuff...
> mm.match('.clojure.sh')
true
```

so the problems is `new minimatch.Minimatch('.*.sh', {dot: true})` works, but
`minimatch('.*.sh', '.clojure.sh', {dot: true})` doesn't

Am I using `minimatch()` this wrong?

**Comment by ericsciple** [comment]
it looks like the interface (at least now) is `function minimatch (p, pattern, options)`

the following returns `true` for me on version 3.0.3
```js
var minimatch = require('minimatch')
minimatch('.clojure.sh', '.*.sh', {dot:true})
```

**Comment by isaacs** [comment]
You don't need `{dot:true}` if the pattern starts with a dot.  Otherwise, @ericsciple's answer is 100% correct.  (And using dot:true doesn't cause any problems, as long as you're ok with `*` matching `.clojure.sh`)
