### ISSUE TITLE
`**/test/**` can't match `./src/test/a.js`

### ISSUE THREAD

**Issue by XGHeaven** [isaacs/minimatch#82]
as follow

```
> mini('./src/test/a.js', '**/test/**')
false
> mini('src/test/a.js', '**/test/**')
true
```

this is a bug?? or a standard??

**Comment by jods4** [comment]
Without `options.dot`, `**` does not match folders beginning with `.`.
Moreover, I think `**` will never match `.` or `..`, even if `options.dot` is set.
Relevant source code is here:
https://github.com/isaacs/minimatch/blob/master/minimatch.js#L294
To match your first example, you'll want something more explicit like `./**/test/**`

**Comment by thecotne** [comment]
even if this is standard it is not expected behaviour (bug)

**Comment by isaacs** [comment]
You're not wrong about the behavior being weird, but the standard is the intended design, and should be the thing to expect. Take it up with unix, sorry.

**Comment by psphilippe** [comment]
You speake french Isaacs , tu parles français ??

Le sam. 5 févr. 2022 2 h 15 p.m., isaacs ***@***.***> a
écrit :

**Comment by isaacs** [comment]
Je ne parle pas français, désolé. Je ne connais que l'anglais, la langue des signes américaine et un peu d'espagnol terrible.
