### ISSUE TITLE
makeRe 'n/!(axios)/**' result falsely matches 'n/axios/a.js'

### ISSUE THREAD

**Issue by leeyeh** [isaacs/minimatch#83]
``` javascript
var re = makeRe('n/!(axios)/**');
// /^(?:n\/(?!\.)(?=.)(?:(?!(?:axios)$)[^\/]*?)\/(?:(?!(?:\/|^)\.).)*?)$/
re.test('n/axios/a.js')
// true

// correct:
minimatch('n/axios/a.js', 'n/!(axios)/**');
// false
```

**Comment by zhangyaochun** [comment]
I also find this problem

**Comment by isaacs** [comment]
`makeRe` is just a convenience and does not work (in fact, probably _cannot_ work) for all patterns, given that the semantics of `!()` and `**` don't have an exact corollary in pcre (at least, not without negative lookahead and very costly ReDOS problems).
