### ISSUE TITLE
Specifying match only in current dir alongside other patterns

### ISSUE THREAD

**Issue by cantide5ga** [isaacs/minimatch#87]
This may simply be that my approach is off.

This pattern passed to the Glob constructor returns only those png's in the root directory and no deeper:
`'./*.png)'`
*debug*: `./*.png [ [ '.', '*.png' ] ]`

However, including the above along side other patterns does an incorrect split:
`'?(*.js|*.css|./*.png)'`
*debug*: `?(*.js|*.css|./*.png) [ [ '?(*.js|*.css|.', '*.png)' ] ]`

It's crystal clear why it does this - Step 3 in minimatch does a split on / chars.  I can fix this particular logic in this circumstance by instead returning this to `set` in Step 3:
```
return s.replace(/([^\.])\/+/g, "$1\,").split(',');
```
However, this breaks the addition of the globstar and isn't correct logic for a `'./*.png)'` pattern by itself.  I'm still digging through the code and hoping to figure this out but mainly wondering what exactly the set is supposed to look like with my intent here: `'?(*.js|*.css|./*.png)'`

Tips for what the minimatch set would need to look like for this glob?  Or am I just plain using the syntax incorrectly?

**Comment by isaacs** [comment]
Extglob patterns cannot contain slashes. This is working as designed. 

Maybe what you want is a {,,,} brace set instead?

**Comment by cantide5ga** [comment]
Not immediately seeing how a brace set would help me here.  I'll look more into it.

> Extglob patterns cannot contain slashes. This is working as designed.

`'./*.png)'` actually works exactly as I want it to, as mentioned above.  Perhaps this isn't intentional.  How would I correctly express this?

Maybe I need to be more explicit in what I need: `'?(*.js|*.css|files-in-current-dir-root-ending-with-ext)'`

Also I just realized my error in posting this in minimatch.  Should've been [node-glob](https://github.com/isaacs/node-glob).  Sorry about that.

**Comment by cantide5ga** [comment]
FYI I ended up just grabbing everything and using the ignore option to git rid of what I didn't need.
```
var pattern = '?(*.js|*.css|*.png)';
var options = {
    ignore: [
        '*/**/*.png'
        ]
};
```
Hopefully someone will point out if this is a butchered way of going about this.

**Comment by cantide5ga** [comment]
Reasonable motivation for the behavior I was fighting up top.  Thanks a lot!
